name: sp_client
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  flutter_bloc:
    path: packages/flutter_bloc
  intl: ^0.15.8
  equatable: ^0.4.0
  grpc: ^2.0.0+1
  uuid: ^2.0.2
  transparent_image: ^0.1.0
  outline_material_icons:
    path: packages/outline_material_icons
  material_design_icons_flutter:
    path: packages/material_design_icons_flutter
  rich_text_editor:
    git:
      url: https://github.com/namhyun-gu/flutter_rich_text_editor
      ref: flutter_web
  # Firebase
  firebase: ^5.0.4

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
