name: sp_client
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  flutter_bloc:
    path: packages/flutter_bloc
  intl: ^0.15.8
  equatable: ^0.4.0
  grpc: ^2.0.0+1
  uuid: ^2.0.2
  transparent_image: ^1.0.0
  diff_match_patch:
    path: packages/diff_match_patch
  # Widgets
  outline_material_icons:
    path: packages/outline_material_icons
  flutter_staggered_grid_view:
    path: packages/flutter_staggered_grid_view
  # Firebase
  firebase: ^5.0.4

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
