name: flutter_bloc
description: Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
version: 0.13.0
author: felix.angelov <felangelov@gmail.com>
homepage: https://felangel.github.io/bloc

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  bloc: ^0.13.0
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  test: ">=1.3.0 <2.0.0"

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
